### 测试GPU环境

In [1]:
import torch
torch.cuda.is_available()

True

### 2.1 创建Tensor

* 创建一个5*3的未初始化的Tensor

In [38]:
# 导入PyTorch
import torch

x = torch.empty(5,3) 
print(x)

tensor([[9.8737e+17, 4.5678e-41, 1.4650e-34],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 7.7052e+31, 7.2148e+22],
        [1.5766e-19, 1.0256e-08, 6.4456e-10]])


* 创建一个5*3的随机初始化的Tensor

In [39]:
x = torch.rand(5,3)
print(x)

tensor([[0.9516, 0.9004, 0.9236],
        [0.7589, 0.9159, 0.3578],
        [0.3043, 0.1507, 0.2551],
        [0.9982, 0.4159, 0.6439],
        [0.4995, 0.4632, 0.8104]])


* 创建一个5*3的long型全0 Tensor

In [40]:
all_zero = torch.zeros(5,3,dtype=torch.long)
print(all_zero)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


* 直接通过数据赋值

In [41]:
given_data = torch.tensor([5.5,3])
print(x)

tensor([[0.9516, 0.9004, 0.9236],
        [0.7589, 0.9159, 0.3578],
        [0.3043, 0.1507, 0.2551],
        [0.9982, 0.4159, 0.6439],
        [0.4995, 0.4632, 0.8104]])


* 使用现有数据赋值

In [43]:
x_old = x.new_ones(5,3,dtype=torch.float64)

In [44]:
x_new = torch.randn_like(x_old,dtype=torch.float) # 与x_old具有相同的shape
print(x_old)
print(x_new)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 2.0230,  1.4832, -0.1010],
        [-1.1281, -2.2422, -0.2314],
        [ 0.9675, -0.4843,  1.7146],
        [ 0.2568,  1.1536, -1.0325],
        [-1.6559, -0.4516, -1.8088]])


* 使用size()或shape来获得Tensor维度

In [45]:
print(x_old.size())
print(x_new.shape)

torch.Size([5, 3])
torch.Size([5, 3])


### 2.2 操作Tensor

#### （1）算术运算

* 加法1

In [48]:
x = x.new_ones(5,3)
y = torch.rand(5,3)
print(x+y)

tensor([[1.7590, 1.9907, 1.8177],
        [1.2072, 1.8388, 1.9061],
        [1.8947, 1.1533, 1.1879],
        [1.8255, 1.6407, 1.1454],
        [1.3005, 1.5951, 1.5679]])


* 加法2

In [49]:
print(torch.add(x,y))

tensor([[1.7590, 1.9907, 1.8177],
        [1.2072, 1.8388, 1.9061],
        [1.8947, 1.1533, 1.1879],
        [1.8255, 1.6407, 1.1454],
        [1.3005, 1.5951, 1.5679]])


In [50]:
# 指定输出
result = torch.empty(5,3) # 必须先定义，类似于强类型语言
torch.add(x,y,out=result)
print(result)

tensor([[1.7590, 1.9907, 1.8177],
        [1.2072, 1.8388, 1.9061],
        [1.8947, 1.1533, 1.1879],
        [1.8255, 1.6407, 1.1454],
        [1.3005, 1.5951, 1.5679]])


* 加法3

In [51]:
y.add_(x) # 改变了y的值
print(y)

tensor([[1.7590, 1.9907, 1.8177],
        [1.2072, 1.8388, 1.9061],
        [1.8947, 1.1533, 1.1879],
        [1.8255, 1.6407, 1.1454],
        [1.3005, 1.5951, 1.5679]])


#### （2）索引：

In [54]:
x = x.new_ones(5,3)
print(x)
y = x[0,:]
y = y+1
print(y)
print(x[0,:]) # 源x并未修改，与课本不一致，说明索引出来的结果与原数据并没有共享内存

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([2., 2., 2.])
tensor([1., 1., 1.])


#### （3）改变形状

* 通过view改变形状

In [96]:
x = torch.rand(5,3)
print(x)
y = x.view(15)
z = x.view(-1,5) # -1表示的维度是根据其他维度的值计算出来的
print(y),print(z)

tensor([[0.5388, 0.3228, 0.7689],
        [0.9215, 0.2115, 0.8622],
        [0.0365, 0.1307, 0.1349],
        [0.7190, 0.5224, 0.7970],
        [0.1132, 0.6644, 0.5514]])
tensor([0.5388, 0.3228, 0.7689, 0.9215, 0.2115, 0.8622, 0.0365, 0.1307, 0.1349,
        0.7190, 0.5224, 0.7970, 0.1132, 0.6644, 0.5514])
tensor([[0.5388, 0.3228, 0.7689, 0.9215, 0.2115],
        [0.8622, 0.0365, 0.1307, 0.1349, 0.7190],
        [0.5224, 0.7970, 0.1132, 0.6644, 0.5514]])


(None, None)

* view()返回的数据与源数据共享data，view仅仅是改变对张量的观察角度，内部数据并未改变

In [97]:
x += 1
print(x)
print(y)
print(id(x)==id(y))
print(id(x)==id(x.view(15)))

tensor([[1.5388, 1.3228, 1.7689],
        [1.9215, 1.2115, 1.8622],
        [1.0365, 1.1307, 1.1349],
        [1.7190, 1.5224, 1.7970],
        [1.1132, 1.6644, 1.5514]])
tensor([1.5388, 1.3228, 1.7689, 1.9215, 1.2115, 1.8622, 1.0365, 1.1307, 1.1349,
        1.7190, 1.5224, 1.7970, 1.1132, 1.6644, 1.5514])
False
False


* 使用clone创造一个副本然后再使用view

In [65]:
x_cp = x.clone()
y = x_cp.view(15)
x += 1
print(x)
print(y)

tensor([[3.0373, 3.7849, 3.0534],
        [3.4876, 3.7183, 3.2063],
        [3.9114, 3.1333, 3.7305],
        [3.7558, 3.5168, 3.0354],
        [3.3139, 3.4477, 3.7193]])
tensor([2.0373, 2.7849, 2.0534, 2.4876, 2.7183, 2.2063, 2.9114, 2.1333, 2.7305,
        2.7558, 2.5168, 2.0354, 2.3139, 2.4477, 2.7193])


* 将一个标量Tensor转换为一个Python number

In [67]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.2223])
-1.2223304510116577


#### （4）广播：适当复制元素使两个Tensor形状相同再按元素运算

In [69]:
# 当形状不同的Tensor进行元素计算时，可能会触发广播机制
x = torch.arange(1,3).view(1,2)
print(x)

y = torch.arange(1,4).view(3,1)
print(y)

print(x+y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


### 2.3 运算内存开销

* 索引操作并不会开辟新内存；

* y=x+y这样的运算将开辟新的内存，而后将y指向新内存；

测试思路：
* 使用python自带的id函数；
* 如果两个Tensor的ID一致，说明对应的内存地址相同，反之不同

In [79]:
x = torch.tensor([1,2])
y = torch.tensor([3,4])

id_before = id(y)
y = x + y;
print(id_before)
print(id(y))

140001384442592
140001384442752


In [90]:
id_before = id(y)
y = y.view(2)

print(id(y) == id_before)

False


In [92]:
# 通过索引指定结果到原来的内存
x = torch.tensor([1,2])
y = torch.tensor([3,4])

id_before = id(y)
y[:] = x+y
print(id(y)==id_before)

True


In [100]:
# 使用torch.add达到上述效果
x = torch.tensor([1,2])
y = torch.tensor([3,4])

id_before = id(y)
torch.add(x,y,out=y)
print(id(y)==id_before) # True

True


In [101]:
# 使用+=达到上述效果
x = torch.tensor([1,2])
y = torch.tensor([3,4])

id_before = id(y)
y += x
print(id(y)==id_before) # True

True


In [102]:
# 使用add_()达到上述效果
x = torch.tensor([1,2])
y = torch.tensor([3,4])

id_before = id(y)
y.add_(x);
print(id(y)==id_before) # True

True


In [105]:
# view虽然与源Tensor共享data,但却是一个新的Tensor，因为除了data还有其他一些属性
y = torch.tensor([3,4])
id_before = id(y)
print(id(y)==id(y.view(2))) # False

False


### 2.4 Tensor与Numpy互相转换

* Tensor 转 Numpy

In [108]:
# 使用numpy()将Tensor转化为Numpy，两者共享内存
a = torch.ones(2,5)
b = a.numpy();
print(a,b)

a += 1
print(a,b)

b += 1
print(a,b)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]) [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]) [[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]
tensor([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]]) [[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]


* Numpy 转 Tensor

In [112]:
# 使用from_numpy()将numpy转化为Tensor，两者共享内存
import numpy as np
a = np.ones([2,5])
b = torch.from_numpy(a)
print(a,b)

a += 1
print(a,b)

b += 1
print(a,b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]] tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]], dtype=torch.float64)
[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]] tensor([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]], dtype=torch.float64)


In [120]:
# 使用torch.tensor()将numpy转化为Tensor，两者不共享内存
c = torch.tensor(a)
a += 1
print(a,c)

[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]] tensor([[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]], dtype=torch.float64)


### 2.5 自动求梯度

* requires_grad：设置为True，则开始追踪；

* Function：Tensor的grad_fn属性值表示创建该Tensor的Function

In [2]:
import torch
x = torch.ones(2,2,requires_grad=True)
print(x)
print(x.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


In [6]:
# 加法操作
y = x+2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


x是直接创建的，没有grad_fn，称为叶子节点；y是通过加法操作得到的，所以有一个值为<AddBackward>的grad_fn

In [5]:
print(x.is_leaf,y.is_leaf)

True False


In [18]:
# 更复杂的操作
z = y*y*3
out = z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


**注意：** requires_grad属性可以使用requires_grad_()函数来修改

In [19]:
import torch
a = torch.randn(2,2) # requires_grad默认值为False
b = ((a*3)) / (a-1)

print(a.requires_grad) # False
print(b.grad_fn) # required_grad为False，所以grad_fn为空

a.requires_grad_(True)
print(a.requires_grad) # True
b = (a*a).sum()
print(b.grad_fn)

False
None
True


* backward()：完成梯度计算，将Tensor梯度记录在grad属性中；

In [33]:
import torch
x = torch.ones(2,2,requires_grad=True)
y = x+2
z = y*y*3
out = z.mean()
print(x.grad)
out.backward() # 等价于out.backward(torch.tensor(1.0))
print(x.grad)

None
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


**注1：**$$out = \frac{1}{4}\sum_{i=1}^43(x_i+2)^2$$
$$\frac{\partial out}{\partial x_i}|_{x_i=1} = \frac{1}{4}6(x_i+2)|_{x_i=1}=4.5$$

**注2：** 假设自变量为向量$x=[x_1,...,x_n]$，对一个向量函数$y=f(x)$，$y$关于$x$的梯度是一个雅可比矩阵：
$$
J = \begin{bmatrix}
\frac{\partial y_1}{\partial x_1}
\end{bmatrix}
$$

In [34]:
out2 = x.sum()
out2.backward()
print(x.grad) # 理论上应该为1
out3 = x.sum()
x.grad.data.zero_() # 每次运行反向传播，梯度都会累加，所以在反向传播之前需要把梯度清零
out3.backward()
print(x.grad)

tensor([[5.5000, 5.5000],
        [5.5000, 5.5000]])
tensor([[1., 1.],
        [1., 1.]])


In [36]:
x = torch.tensor([1.0,2.0,3.0,4.0],requires_grad = True)
y = 2*x
z = y.view(2,2)
print(z)
v = torch.tensor([[1.0,0.1],[0.01,0.001]],dtype=torch.float)
z.backward(v)
print(x.grad)

tensor([[2., 4.],
        [6., 8.]], grad_fn=<ViewBackward0>)
tensor([2.0000, 0.2000, 0.0200, 0.0020])


* detach()：不再追踪；

* with torch.no_grad()：包裹的代码块不会被追踪；

In [39]:
import torch
x = torch.tensor(1.0,requires_grad=True)
y1 = x**2
with torch.no_grad():
    y2 = x**3
y3 = y1 + y2

print(x.requires_grad)
print(y1,y1.requires_grad)
print(y2,y2.requires_grad)
print(y3,y3.requires_grad)

y3.backward()
print(x.grad)

True
tensor(1., grad_fn=<PowBackward0>) True
tensor(1.) False
tensor(2., grad_fn=<AddBackward0>) True
tensor(2.)


注：$$y_3 = y_1 + y_2 = x^2 + x^3$$
$$\frac{d y_3}{dx} := \frac{d y_1}{dx} = 2x$$

**目的：** 想要修改tensor的值，但不希望被记录，可以借助tensor.data

In [41]:
import torch
x = torch.ones(1,requires_grad=True)
print(x.data) # x.data也是一个张量
print(x.data.requires_grad) # 但没有记录

tensor([1.])
False


In [42]:
y = 2*x
x.data *=100

y.backward()
print(x) # 值已修改
print(x.grad) # 梯度保持为2

tensor([100.], requires_grad=True)
tensor([2.])


### Tensor on GPU

In [119]:
# 用to()可以将Tensor在CPU和GPU之间相互移动
x = torch.eye(2)
if torch.cuda.is_available():
    device = torch.device("cuda") # GPU
    y = torch.ones_like(x,device=device) # 直接创建一个在GPU上的Tensor
    x = x.to(device)
    z = x + y;
    print(z)
    print(z.to("cpu",torch.double)) # 同时更改数据类型
    

tensor([[2., 1.],
        [1., 2.]], device='cuda:0')
tensor([[2., 1.],
        [1., 2.]], dtype=torch.float64)
